### ISSUE TITLE
Setup API to Export Data

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-backend#1009]
As an owner of P2, I want to call an API to receive response data for all types of items so that I can build dashboards outside of ML 

Requirements: 
- Need gear on activity list screen to enter IP address 
   - error messages 
- Data collected by applet is live streamed 
- Data is still stored in ML db
-[ LSL ](https://github.com/Outworldz/LSL-Scripts)

**Comment by WorldImpex** [comment]
Currently no requirements

**Comment by natalia-muzyka** [comment]
@jj105 is the "Enable streaming of response data" checkbox is set up for this ticket?
I see it on prod, it is expected? And could you tell me more, how can I test this feature? Thank you!
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/db4bb001-fcec-4b50-9b12-ba5328faf09b)

**Comment by jj105** [comment]
@natalia-muzyka yes, that option is set up for this ticket
it shouldn't be available on prod, I think it might be a deployment issue

in order to test this feature, we need to run socket server on local PC
it is python code [here](https://github.com/ChildMindInstitute/mindlogger-app/blob/master/socket-server.py)
