### ISSUE TITLE
Update to Newest version of Negative Behaviors Calculation 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-backend#1192]
https://docs.google.com/document/d/1roxUCdmofoi7q7f8GsU5pHnnpQS8EYx_E5e2MwBJiDM/edit?usp=sharing

**Comment by natalia-muzyka** [comment]
@jj105 @WorldImpex 
Selecting the negative behavior has no impact on earned tokens.
User earns maximum passive tokens per negative behavior the next day(20/01) after selecting the negative behavior the previous day(19/01).

I set up cases from the [latest TL doc] (with changing just ETR)(https://docs.google.com/document/d/1roxUCdmofoi7q7f8GsU5pHnnpQS8EYx_E5e2MwBJiDM/edit#)

---

I have an activity with positive and negative behavior.
The default state is inactive. I have never completed the activity before (didn't make and save any entry)

**Case 1**
TV = 3
ETR = 18:00 - 00:00
Rate = 2h
- 19/01 before the ETR has started (~ at 17:00 per user's timezone) I selected one negative behavior (without adding additional info: e.g. time and 2D slider). I earned 2 tokens per completing the past behavior activity (expected).
- 20/01 I expected to earn +6 tokens, because:
behavior_value = 3 tokens
effective_duration = 360 minutes
time_increment = 120 minutes
negative_behavior_count = 1
negative_tokens_added =  SUM[behavior_value * floor(effective_duration / time_increment)  – behavior_value * negative_behavior_count]
IF: negative_tokens_added < 0 , set negative_tokens_added to 0
6 =  SUM[3 * floor(360 / 120)  – 3 * 1]
**_Actual result:_** I earned +9 tokens (max possible) instead of 6. My total is 11 tokens.


**Case 2**
TV = 3
ETR = 17:00 - 23:00
Rate = 2h
- 19/01 after the ETR has started (~ at 17:30 per user's timezone) I selected one negative behavior (without adding additional info: e.g. time and 2D slider). I earned 2 tokens per completing the past behavior activity (expected).
- 20/01 I expected to earn +3 tokens, because:
behavior_value = 3 tokens
effective_duration = 300 minutes
time_increment = 120 minutes
negative_behavior_count = 1
negative_tokens_added =  SUM[behavior_value * floor(effective_duration / time_increment)  – behavior_value * negative_behavior_count]
IF: negative_tokens_added < 0 , set negative_tokens_added to 0
3 =  SUM[3 * floor(300 / 120)  – 3 * 1]
**_Actual result:_** I earned +6 tokens instead of 3. My total is 8 tokens.


**Case 5**
TV = 3
ETR = 17:30 - 23:30
Rate = 2h
- 19/01 after the ETR has started (~ at 18:00 per user's timezone) I selected 
one negative behavior (without adding additional info: e.g. time and 2D slider)
one positive behavior
I earned 7 tokens (2 per completing the past behavior activity and 5 per positive behavior, as expeted).
- 20/01 I expected to earn +3 tokens, because:
behavior_value = 3 tokens
effective_duration = 300 minutes
time_increment = 120 minutes
negative_behavior_count = 1
negative_tokens_added =  SUM[behavior_value * floor(effective_duration / time_increment)  – behavior_value * negative_behavior_count]
IF: negative_tokens_added < 0 , set negative_tokens_added to 0
3 =  SUM[3 * floor(300 / 120)  – 3 * 1]
**_Actual result:_** I earned +6 tokens instead of 3. My total is 13 tokens.

**Environment:**
ML v0.18.37 staging
Samsung Galaxy S9 // Android 10
iPad Pro (10,5-inch) MQDX2 // iOS 15
user: josephine_ml@protonmail.com // qwertyui
owner: kimberly_ml@protonmail.com // `12345678`
applets:
TL applet CASE 1, 
TL applet CASE 2,
TL applet CASE 3, 
TL applet CASE 4,
TL applet CASE 5
Applet password:	Qwe123!!!

**Comment by natalia-muzyka** [comment]
Works as expected. Cases that are described in the latest [TL document](https://docs.google.com/document/d/1roxUCdmofoi7q7f8GsU5pHnnpQS8EYx_E5e2MwBJiDM/edit#heading=h.tduvrd4t36dn) are passed successfully.

Environment:
ML v0.18.39 staging
Samsung Galaxy S7 // Android 8
iPhone X // iOS 14.6
Samsung Galaxy S9 // Android 10
iPhone XS // iOS 15.2
iPad Pro (10,5-inch) MQDX2 // iOS 15
